#!/bin/bash

clang-format -style='{ Language: Cpp, UseTab: Never, IndentWidth: 4, AlignTrailingComments: true, AlignConsecutiveAssignments: true, AlignAfterOpenBracket: true, AlignEscapedNewlines: Left, AlignOperands: true, AllowShortFunctionsOnASingleLine: Empty, AllowShortIfStatementsOnASingleLine: true, AllowShortLoopsOnASingleLine: true, BreakBeforeBraces: Linux, BreakBeforeTernaryOperators: true, ColumnLimit: 0, FixNamespaceComments: true, SortIncludes: false, MaxEmptyLinesToKeep: 1, SpaceBeforeParens: ControlStatements, IndentCaseLabels: true, DerivePointerAlignment: true }' -dump-config > .clang-format

clang-format -i -verbose ClamBC/*.cpp
clang-format -i -verbose ClamBC/*.c
clang-format -i -verbose ClamBC/*.h
clang-format -i -verbose ClamBC/TargetInfo/*.cpp
clang-format -i -verbose ClamBC/test/*.c
clang-format -i -verbose clang/lib/Headers/bcfeatures.h
clang-format -i -verbose clang/lib/Headers/bytecode*.h
clang-format -i -verbose ifacegen/*.cpp
clang-format -i -verbose ifacegen/*.c
clang-format -i -verbose ifacegen/*.h
clang-format -i -verbose driver/clamdriver/*.cpp
clang-format -i -verbose driver/clamdriver/*.c
clang-format -i -verbose driver/clamdriver/*.h
clang-format -i -verbose driver/main/*.cpp
clang-format -i -verbose driver/main/*.c
clang-format -i -verbose driver/main/*.h

# Undo changes to specific files (whitelist)
git checkout driver/clamdriver/re2c
